version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Affiindia"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kjg18kdb2iot"
s3_prefix = "Affiindia"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
