AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  

  Sample SAM Template for 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  AffiIndiaData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      # Events:
      #   CheckWebsiteScheduledEvent:
      #     Type: Schedule
      #     Properties:
      #       Schedule: rate(1 day)
  
  # MyNewEventsRule:
  #   Type: 'AWS::Events::Rule'
  #   Properties:
  #     Description: Test Events Rule
  #     RoleArn : 'arn:aws:iam::676409062562:role/temprole'
  #     ScheduleExpression: rate(1 day)
      
  #     State: ENABLED
  #     Targets:
  #       - Arn: !GetAtt AffiIndiaData.Arn
  #         Id: Id1234
  #         RetryPolicy:
  #           MaximumRetryAttempts: 4
  